### ISSUE TITLE
can't pickle _thread.RLock objects

### ISSUE THREAD

**Issue by ro-hit81** [sentinel-hub/norsc19-eo-learn-workshop#10]
I was going through the binder for the introduction part. For EOExecutor task, whenever the value for workers=3, I am getting an error. It is not allowing parallel process. It works fine for worker =1 & it should do but changing to greater than 1 is giving error.

`_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/srv/conda/envs/notebook/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<ipython-input-44-2dc4e3d6aaa3> in <module>
     11 executor = EOExecutor(workflow, execution_args, save_logs=True, logs_folder=OUTPUT_FOLDER)
     12 
---> 13 executor.run(workers=3)  # The execution will use at most 3 parallel processes

/srv/conda/envs/notebook/lib/python3.7/site-packages/eolearn/core/eoexecution.py in run(self, workers, multiprocess, return_results)
    144             with pool_executor_class(max_workers=workers) as executor:
    145                 self.execution_stats = list(tqdm(executor.map(self._execute_workflow, processing_args),
--> 146                                                  total=len(processing_args)))
    147 
    148         self.general_stats = self._prepare_general_stats(workers, processing_type)

/srv/conda/envs/notebook/lib/python3.7/site-packages/tqdm/notebook.py in __iter__(self, *args, **kwargs)
    216     def __iter__(self, *args, **kwargs):
    217         try:
--> 218             for obj in super(tqdm_notebook, self).__iter__(*args, **kwargs):
    219                 # return super(tqdm...) will not catch exception
    220                 yield obj

/srv/conda/envs/notebook/lib/python3.7/site-packages/tqdm/std.py in __iter__(self)
   1127 
   1128         try:
-> 1129             for obj in iterable:
   1130                 yield obj
   1131                 # Update and possibly print the progressbar.

/srv/conda/envs/notebook/lib/python3.7/concurrent/futures/process.py in _chain_from_iterable_of_lists(iterable)
    481     careful not to keep references to yielded objects.
    482     """
--> 483     for element in iterable:
    484         element.reverse()
    485         while element:

/srv/conda/envs/notebook/lib/python3.7/concurrent/futures/_base.py in result_iterator()
    596                     # Careful not to keep a reference to the popped future
    597                     if timeout is None:
--> 598                         yield fs.pop().result()
    599                     else:
    600                         yield fs.pop().result(end_time - time.monotonic())

/srv/conda/envs/notebook/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
    426                 raise CancelledError()
    427             elif self._state == FINISHED:
--> 428                 return self.__get_result()
    429 
    430             self._condition.wait(timeout)

/srv/conda/envs/notebook/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

/srv/conda/envs/notebook/lib/python3.7/multiprocessing/queues.py in _feed(buffer, notempty, send_bytes, writelock, close, ignore_epipe, onerror, queue_sem)
    234 
    235                         # serialize the data before acquiring the lock
--> 236                         obj = _ForkingPickler.dumps(obj)
    237                         if wacquire is None:
    238                             send_bytes(obj)

/srv/conda/envs/notebook/lib/python3.7/multiprocessing/reduction.py in dumps(cls, obj, protocol)
     49     def dumps(cls, obj, protocol=None):
     50         buf = io.BytesIO()
---> 51         cls(buf, protocol).dump(obj)
     52         return buf.getbuffer()
     53 

TypeError: can't pickle _thread.RLock objects`

**Comment by batic** [comment]
Hi @ro-hit81,

I am not sure how much multiprocessing one can really do with binder, as the resources on binder are very limited. 

If you'd like to run anything more demanding, I advise you to clone the repository, install needed packages and run from your computer (a computer you have access to, it could also be an AWS EC2 instance...)

All the best!
